[package]
name = "rosalind"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.10"
generalized_suffix_tree = "1.2.1"
itertools = "0.12.1"
regex = "1.10.3"


[dependencies.reqwest]
version = "0.11.24"
features = ["blocking"]