[package]
name = "rosalind"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.16"
generalized_suffix_tree = "1.2.1"
itertools = "0.13.0"
regex = "1.10.3"


[dependencies.reqwest]
version = "0.12.7"
features = ["blocking"]